# Generated by Django 5.1.2 on 2024-12-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('trending', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='images/catagory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
