# Generated by Django 5.1.2 on 2024-12-15 15:00

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(null=True, upload_to=home.models.getFileName),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('actuall_price', models.FloatField(blank=True, null=True)),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to=home.models.getFileName)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trending', models.BooleanField(default=False)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.catagory')),
            ],
        ),
    ]
